name: Drupal coding standards

on: [push]

jobs:
  phpcs-drupal:
      name: Drupal coding standards
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: guix77/phpcs-drupal-action@php8.4RC3
